### ISSUE TITLE
If the amount is higher then the count, shouldn't there be a trigger for producing more coffees? Maybe i didn't understand the workflow completely here.

### ISSUE THREAD

**Issue by RenschS** [guysneh/CoffeeEnterprise#2]
https://github.com/guysneh/CoffeeEnterprise/blob/f81e2bced71fd695ba4ad727c31bf79f78c52f33/Store/Controllers/StoreController.cs#L149

**Comment by guysneh** [comment]
The idea is that the factory does not know anything about the store. it should just send the coffee to the store.
Of course, one can extend the code so that the store could communicate with the factory too :)
