### ISSUE TITLE
transaction rollback missing?

### ISSUE THREAD

**Issue by RenschS** [guysneh/CoffeeEnterprise#3]
https://github.com/guysneh/CoffeeEnterprise/blob/f81e2bced71fd695ba4ad727c31bf79f78c52f33/Store/Controllers/StoreController.cs#L184

**Comment by guysneh** [comment]
no need, the transaction will auto-rollback when disposed if either commands fails ;) 
 
 https://docs.microsoft.com/en-us/ef/core/saving/transactions
